name: Verus Miner (Auto & Telegram)

on:
  schedule:
    - cron: "0 */5 * * *"  # Auto-run tiap 5 jam
  workflow_dispatch:

jobs:
  verusmine:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # Force stop tiap 5 jam

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git cmake automake libtool autoconf pkg-config \
            libcurl4-openssl-dev screen

      - name: Clone & build ccminer
        run: |
          git clone https://github.com/monkins1010/ccminer.git
          cd ccminer
          chmod +x build.sh
          ./build.sh

      - name: Start mining
        run: |
          cd ccminer

          # Konfigurasi
          WALLET="RGVmtuvrP2yX8q3U4up77CcSpkcVhp4bUG"
          POOL="stratum+tcp://na.luckpool.net:3956"
          THREADS=2
          WORKER="GH-${{ github.run_id }}"
          LOG_FILE="log.txt"
          MAX_IDLE=600  # 10 menit

          TELEGRAM_TOKEN="7548058927:AAF-fL3P6W5sNxbzbmwwtsfVxPZubdIybzc"
          TELEGRAM_CHAT_ID="5763229296"

          send_telegram() {
            curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
              -d chat_id=${TELEGRAM_CHAT_ID} \
              -d parse_mode=Markdown \
              -d text="$1"
          }

          send_telegram "⛏️ *Mining dimulai* di *$WORKER* dengan $THREADS thread."

          # Mulai mining di background
          rm -f "$LOG_FILE"
          ./ccminer -a verus -o $POOL -u $WALLET.$WORKER -p x -t $THREADS | tee "$LOG_FILE" &
          PID=$!
          LAST_ACCEPTED=$(date +%s)

          # Monitoring loop
          while sleep 60; do
            if ! kill -0 $PID 2>/dev/null; then
              send_telegram "❌ *Miner crash* di *$WORKER*."
              exit 1
            fi

            LAST_LINE=$(tail -n 1 "$LOG_FILE")
            NOW=$(date +%s)

            if echo "$LAST_LINE" | grep -q "accepted"; then
              LAST_ACCEPTED=$NOW
            fi

            DIFF=$((NOW - LAST_ACCEPTED))
            if [ $DIFF -gt $MAX_IDLE ]; then
              send_telegram "⚠️ *Tidak ada share diterima* selama 10 menit. Restarting miner di *$WORKER*..."
              kill $PID
              break
            fi
          done

          SHARES=$(grep -c "accepted" "$LOG_FILE")
          send_telegram "✅ *Mining selesai* di *$WORKER*. Total accepted shares: *$SHARES*"
