name: Verus Miner (Auto‑Restart + Live Share + CPU)

on:
  schedule:
    - cron: "0 */5 * * *"   # setiap 5 jam
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 300     # 5 jam

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git build-essential cmake automake libtool autoconf pkg-config \
            libcurl4-openssl-dev screen sysstat

      - name: Clone & build cpuminer‑verus2 (CPU‑only)
        run: |
          git clone https://github.com/monkins1010/veruscoin-cpuminer.git cpuminer
          cd cpuminer
          ./build.sh

      - name: Start mining
        run: |
          cd cpuminer

          # ===== Konfigurasi =====
          WALLET="RGVmtuvrP2yX8q3U4up77CcSpkcVhp4bUG"
          POOL="stratum+tcp://na.luckpool.net:3956"
          THREADS=2
          WORKER="GH-${{ github.run_id }}"
          LOG_FILE="log.txt"
          MAX_IDLE=600            # 10 menit

          TELOK="7548058927:AAF-fL3P6W5sNxbzbmwwtsfVxPZubdIybzc"
          CHAT="5763229296"

          send() {
            curl -s -X POST "https://api.telegram.org/bot${TELOK}/sendMessage" \
              -d chat_id="${CHAT}" \
              -d parse_mode=Markdown \
              -d text="$1" >/dev/null
          }

          cpu_usage() {
            LOAD=$(grep -oP 'load average: \K[0-9.]+' < /proc/loadavg)
            TEMP=$(sensors 2>/dev/null | grep -m1 -oP '\+?\d+(\.\d+)?°C' || echo "N/A")
            echo "\n🧠 CPU load: *$LOAD*, Temp: *$TEMP*"
          }

          send "⛏️ *Mining dimulai*\nWorker: *$WORKER*\nThreads: *$THREADS*$(cpu_usage)"

          : > "$LOG_FILE"
          ./cpuminer -a verus -o $POOL -u $WALLET.$WORKER -p x -t $THREADS 2>&1 | tee -a "$LOG_FILE" &
          PID=$!
          LAST_ACCEPT=$(date +%s)
          LAST_CPU=$(date +%s)

          while sleep 10; do              # loop 10‑detik
            [ -e /proc/$PID ] || { send "❌ *Miner crash* di *$WORKER*"; exit 1; }

            LINE=$(tail -n1 "$LOG_FILE")
            NOW=$(date +%s)

            # Live notifikasi jika share
            if echo "$LINE" | grep -q "accepted"; then
              LAST_ACCEPT=$NOW
              SHARE_NO=$(grep -c "accepted" "$LOG_FILE")
              send "✅ *Share #$SHARE_NO* diterima oleh *$WORKER*"
            fi

            # Kirim CPU usage setiap jam
            if (( NOW - LAST_CPU >= 3600 )); then
              send "⏱ *1‑hour update*$(cpu_usage)"
              LAST_CPU=$NOW
            fi

            # Restart jika idle
            if (( NOW - LAST_ACCEPT > MAX_IDLE )); then
              send "⚠️ *Tidak ada share 10 menit* – restart miner di *$WORKER*"
              kill $PID
              break
            fi
          done

          TOTAL=$(grep -c "accepted" "$LOG_FILE")
          send "✅ *Session selesai*\nWorker: *$WORKER*\nTotal share: *$TOTAL*$(cpu_usage)"
